// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Return Ibrahim Mahmud's public profile: name, stage, discipline, and contact email.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: "Ibrahim Mahmud",
      stage: "Class 10 Student \u2014 SSC 2027 Candidate",
      discipline: "Cybersecurity Enthusiast",
      email: "x.ibrahimmahmud@gmail.com",
      status: "Active \u2014 revisions ongoing",
      method: "Learn by taking things apart \u2014 networks, code, and the odd puzzle \u2014 then rebuild them correctly"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_skills_default = defineTool2({
  name: "list_skills",
  title: "List core skills",
  description: "List Ibrahim's core skills with proficiency level and approximate progress percentage.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const skills = [
      { name: "Cyber Security", level: "Learning", progress: 25 },
      { name: "AI Productivity", level: "Advanced", progress: 80 },
      { name: "Vibe Coding", level: "Intermediate", progress: 60 },
      { name: "Security Tools", level: "Hands-on", progress: 55 }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(skills, null, 2) }],
      structuredContent: { skills }
    };
  }
});

// src/lib/mcp/tools/list-learning.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_learning_default = defineTool3({
  name: "list_learning",
  title: "List current learning modules",
  description: "List the topics Ibrahim is currently learning.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const modules = [
      { id: "01", title: "Cyber Security", detail: "Networks, defenses, offensive fundamentals \u2014 one lab at a time." },
      { id: "02", title: "AI", detail: "Prompting, agents, and using models as leverage for real work." },
      { id: "03", title: "Programming", detail: "Web fundamentals, scripting, and shipping small tools that solve problems." }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(modules, null, 2) }],
      structuredContent: { modules }
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_contact_default = defineTool4({
  name: "get_contact",
  title: "Get contact info",
  description: "Return ways to reach Ibrahim Mahmud \u2014 email and social links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const contact = {
      email: "x.ibrahimmahmud@gmail.com",
      website: "https://ibrahimpro.lovable.app",
      contactForm: "https://ibrahimpro.lovable.app/#contact"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
      structuredContent: contact
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ibrahim-portfolio-mcp",
  title: "Ibrahim Mahmud \u2014 Portfolio",
  version: "0.1.0",
  instructions: "Public MCP server for Ibrahim Mahmud's portfolio. Use these tools to look up his profile, current skills, what he is learning, and how to contact him.",
  tools: [get_profile_default, list_skills_default, list_learning_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
